model:
  _target_: speed.networks.dit.DiT_B_2
  num_classes: ${num_classes}

diffusion:
  _target_: speed.diffusion.iddpm.IDDPM
  timestep_respacing: ""
  faster: true

data:
  _target_:
  dataset:
    _target_: speed.dataset.image.image_dataest
    root: "root_path_dataset_ImageNet"
    image_size: ${image_size}

  batch_size: 32
  num_workers: 4

max_iters: 1000000
