model:
  _target_: speed.networks.unet.create_unet_model
  input_size: 32
  num_channels: 128
  num_res_blocks: 3
  num_classes: 1000
  class_cond: true


diffusion:
  _target_: speed.diffusion.speed.Speed_IDDPM
  timestep_respacing: ""
  weighting: ours
  sampling: ours
  k: 5
  lam: 0.6
  tau: 700

experiment_dir: outputs/imagenet/unet_faster
