data:
  dataset:
    root: /home/wangkai/big_space/SamJ/data/imagenet/train

diffusion:
  _target_: speed.diffusion.speed.Speed_IDDPM
  timestep_respacing: ""
  weighting: ours
  sampling: ours
  k: 2
  lam: 0.6
  tau: 700

experiment_dir: outputs/abl_imagenet/base

model:
  _target_: speed.networks.dit.DiT_S_8
  condition: none