diffusion:
  _target_: speed.diffusion.speed.Speed_IDDPM
  timestep_respacing: ""
  weighting: theory

vae:
  _target_: diffusers.models.AutoencoderKL.from_pretrained
  pretrained_model_name_or_path: transformers/sd-vae-ft-ema

data:
  dataset:
    root: "root_path_dataset"

experiment_dir: outputs/metfaces/theory
