diffusion:
  _target_: speedit.diffusion.speed.Speed_IDDPM
  timestep_respacing: ""
  weighting: theory

experiment_dir: outputs/unet/ffhq/faster

data:
  dataset:
    root: "/data1/xinpeng/ffhq/images256x256"
